name = "wx-api"
main = "dist/index.js"
compatibility_date = "2024-12-27"

routes = [
  { pattern = "your.domain.com", custom_domain = true }
]

kv_namespaces = [
  { binding = "DB", id = "your-kv-db-id" }
]

[ai]
binding = "AI"

[vars]
AppID = "your-appid"
AppToken = "your-token"
AppSecret = "your-secret"
AppAesKey = "your-aes-key"
AesMode = "OFF"
InitAuth = "your-init-auth"
AllowOrigin = "your-front-allow-list"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 15, period = 10 }
